### PR TITLE
Add `andMap` for applicative apply in Elm

### PR DESCRIPTION
**Pull request by zwilias**
Also added proper links to forward/backwards function application in Elm.

### CODE REVIEW

**Comment by hakonrossebo** [comment]
Thanks - the other fixes looks ok, but I cannot find any documentation on andMap in Elm - to my knowledge there is no apply in Elm, its handled by map2, map3 ++.

**Comment by hakonrossebo** [comment]
I see there are some extra packages supporting andMap, maybe we can put some information about this in the details/link section.

http://klaftertief.github.io/elm-search/?q=andMap

**Comment by hakonrossebo** [comment]
Accepted PR - thanks. Will add a * with reference to notes for explanation

**Comment by zwilias** [comment]
Yeah, it's by no means official (since packages are free to call their functions whatever they wish, so for `pure`, you'll have `singleton`, `succeed` and a few others), but `andMap` has become a bit of a defacto standard: http://klaftertief.github.io/elm-search/?q=andMap

**Comment by hakonrossebo** [comment]
Nice to know :) - At first, I could not understand why I could not find your changes, but noticed that you had commited to the /docs folder thats beeing cleared for each release - guess I need to find a better solution to avoid confusion :)

**Pull request merged**
